### ISSUE TITLE
Pom properties

### ISSUE THREAD

**Issue by danielbarela** [j256/ormlite-jdbc#14]
In the pom properties, commons-logging and log4j are specified twice with different versions.  
```xml
<commons-logging-version>1.1.1</commons-logging-version>
<commons-logging-version>1.1</commons-logging-version>

<log4j-version>1.2.15</log4j-version>
<log4j-version>1.2.12</log4j-version>
```
Is there a reason for this or can they be collapsed into one property?

Thanks

**Comment by j256** [comment]
FIxed.  Thanks.  See: https://github.com/j256/ormlite-jdbc/commit/42e4042f3da29bd38fe9f8ae474abb724eb21a85
