### ISSUE TITLE
Get all open connections to DB

### ISSUE THREAD

**Issue by benedekh** [j256/ormlite-jdbc#16]
Dear All,

Is there any way to get all _open_ connections to a database made via the [ConnectionSource](https://github.com/j256/ormlite-jdbc/blob/master/src/main/java/com/j256/ormlite/jdbc/JdbcConnectionSource.java) in ORMLite v4.48?

Cheers,
Ben

**Comment by j256** [comment]
Not with the code checked in.  You can certainly extend the `ConnectionSouce` you are using and add that feature however.  Take a look at: [JdbcConnectionSource.setDatabaseConnectionProxyFactory(...) ](http://ormlite.com/javadoc/ormlite-jdbc/com/j256/ormlite/jdbc/JdbcConnectionSource.html#setDatabaseConnectionProxyFactory(com.j256.ormlite.support.DatabaseConnectionProxyFactory)).

**Comment by benedekh** [comment]
Thank you.
