### ISSUE TITLE
Ormlite 4.48 + MySQL Connector 6.0.2

### ISSUE THREAD

**Issue by fromgate** [j256/ormlite-jdbc#18]
I'm using ORMLite 4.48 and MySQL Connector 6.02 and receive this error message:

> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is`com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
> Mon Jul 25 13:16:47 MSK 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

As I can understand this message is related to fact ORMLite was not updated on maven since 2013. Will it be updated?

**Comment by hoangtranwork** [comment]
hello, I'm also using the same version of ormlite/connector and found a way for this to work (somewhat a workaround):
I have a somewhat dummy class to hold the new driver class name:
https://gist.github.com/hoangtranwork/0128142973597904237d814f6ac0b4b6
And then I use it to create a connectionSource:
https://gist.github.com/hoangtranwork/b6ebc1d64f5c858945c157d8fa5d0def

Note: for all the other setting (useSL=false, ...) I set it with HikariCP

**Comment by j256** [comment]
Wow.  Old issue.  Sorry for the delay.

Any idea how I can programmatically determine if I need to load the driver or not?

**Comment by hoangtranwork** [comment]
a few days ago I found out that I no longer need to use the dummy class, the `MysqlDatabaseType` (which is now moved to jdbc package) already has its driver class name up-to-date. So I believe we can close this issue.

**Comment by j256** [comment]
Thanks @hoangtranwork .
