### ISSUE TITLE
Nested transactions don't work

### ISSUE THREAD

**Issue by maroux** [j256/ormlite-jdbc#19]
You would expect that at the end of this block:

```
    TransactionManager.callInTransaction(connectionSource, new Callable<Object>() {
        @Override
        public Object call() throws Exception {
            doQueryA();

            OrmDao.runTransaction(new Callable<Object>() {
                @Override
                public Object call() throws Exception {
                    doQueryB();
                    return null;
                }
            });
            throw new SQLException();
        }
    });
```

effects of `doQueryB` aren't visible in the DB - but that is not true. The inner `runTransaction` calls `connection.commit()` ([here](https://github.com/j256/ormlite-jdbc/blob/master/src/main/java/com/j256/ormlite/jdbc/JdbcDatabaseConnection.java#L104)) which **commits** the whole transaction, and thus the rollback on raising `SQLException` is unable to undo the effects of inner transaction. (I tested on Postgres 9.3 if it matters).

The correct way of doing this (from the [docs](https://www.postgresql.org/docs/9.5/static/sql-release-savepoint.html)) is:

```
BEGIN;
    INSERT INTO table1 VALUES (3);
    SAVEPOINT my_savepoint;
    INSERT INTO table1 VALUES (4);
    RELEASE SAVEPOINT my_savepoint;
COMMIT;
```

So, it should call `releaseSavepoint` if the savepoint depth is >=1, or `commit` if savepoint depth is zero. Yes, `TransactionManager` has to track all savepoints in a stack.

I can try and write a patch for this if there's interest in fixing this. Even if this is isn't fixed, the documentation should be updated to reflect that nested transactions don't work as one would expect.

**Comment by j256** [comment]
Huh.  Wow.  Should have fixed this long ago.  I've moved this to ormlite.core.

**Comment by j256** [comment]
Moved to https://github.com/j256/ormlite-core/issues/129 .  Code to handle this is in 5.1.  See: https://github.com/j256/ormlite-core/commit/2163945b66fec803a12e6da4697496737e58e0e6
