### ISSUE TITLE
Having trouble with SimpleMain.java in IntelliJ

### ISSUE THREAD

**Issue by taratemima** [j256/ormlite-jdbc#21]
I downloaded the code for SimpleMain and opened it in IntelliJ 2016.3.4. I got an error message about 'import com.j256.ormlite.jdbc.JdbcConnectionSource' not being available. I did a search for the jar file on the web and got the error message that it could not be found.

**Comment by j256** [comment]
How about you spend maybe a minute RTFM?  http://ormlite.com/docs/getting-started
