### ISSUE TITLE
Logging with java.util.logger

### ISSUE THREAD

**Issue by juehv** [j256/ormlite-jdbc#22]
Hi,
I want ormlite to use java.util.logger as default logger. I found the JavaUtilLog class but no way to configure it, because the LoggerFactory does not support this logging type. Is there a way?

Cheers.

**Comment by j256** [comment]
Interesting.  I guess I always assumed that no one would want to use JavaUtilLog.  I've added it into the mix however with it's own type but it won't ever be chosen by default.

**Comment by j256** [comment]
I moved it to -core as well.  See: https://github.com/j256/ormlite-core/commit/661d20e13f11ecd4044e690a3ca98a1d4eadc308
