### ISSUE TITLE
Column Sizes Shrinking

### ISSUE THREAD

**Issue by kmccmk9** [j256/ormlite-jdbc#27]
Hello, I'm trying to implement this library into my project. I'm running into this issue where I get the following error:
`
java.sql.SQLException: Unable to run insert stmt on object com.gmail.kyle.corsi.helpmeadvancedsponge.database.schemas.Ticket@5dfdaaf8: INSERT INTO `tickets` (`status` ,`uuid` ,`x` ,`y` ,`z` ) VALUES (?,?,?,?,?)`

Further down into the stack trace I find the root cause to be:

`Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "UUID VARCHAR(20) NOT NULL": "'33ea4674-f919-44b6-9dca-d5d01a6def51' (36)"`

However, this is where I get confused. From what I gather from this error, it is trying to take my string of 36 characters and insert them into a column with a length of 20 (obviously would throw this error or truncation error). Where it gets confusing for me is that when I execute my createTable call as you have documented on the website and in your example code I see the following output:

```
[23:42:24 INFO] [com.j256.ormlite.table.TableUtils]: creating table 'tickets'
[23:42:24 INFO] [com.j256.ormlite.table.TableUtils]: executed create table statement changed 0 rows:
                 CREATE TABLE IF NOT EXISTS `tickets` (`id` INTEGER AUTO_INCREMENT ,
                 `status` VARCHAR(100) , `uuid` VARCHAR(255) , `x` DOUBLE PRECISION ,
                 `y` DOUBLE PRECISION , `z` DOUBLE PRECISION , PRIMARY KEY (`id`) )
```

As far as I can tell from this output it should be creating a table with all of those columns as a schema. But notice that uuid is set to varchar 255. I do not receive any additional logs or errors about table creation so I am lead to believe it succeeds according to this output. 

Any help or thoughts would be appreciated. Thank you

**Comment by j256** [comment]
Any chance the table already exists @kmccmk9 ?  Can you dump the schema to see the actual columns and how are they defined.  Sounds to be that the uuid field is still 20 characters wide.  Maybe an alter table operation is necessary?

**Comment by kmccmk9** [comment]
@j256 I actually wiped the database before running this test. I can confirm that using an alter statement like:

`_ticketDao.executeRawNoArgs("ALTER TABLE `tickets` ALTER `uuid` SET DATA TYPE varchar(255)");`

Does indeed work. I'm not sure why it generated the field initially at 20 though.

**Comment by j256** [comment]
Hrm.  Can you show me the annotated class?

**Comment by kmccmk9** [comment]
```
package com.gmail.kyle.corsi.helpmeadvancedsponge.database.schemas;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "tickets")
public class Ticket
{
    @DatabaseField(generatedId = true)
    private int id;

    @DatabaseField
    private TicketStatus status;

    @DatabaseField
    private String uuid;

    @DatabaseField
    private double x;

    @DatabaseField
    private double y;

    @DatabaseField
    private double z;

    public Ticket() {

    }

    public enum TicketStatus {
        Open,
        Closed,
        Pending,
        Other
    }

    public int getId ()
    {
        return id;
    }

    public void setId (int id)
    {
        this.id = id;
    }

    public TicketStatus getStatus ()
    {
        return status;
    }

    public void setStatus (TicketStatus status)
    {
        this.status = status;
    }

    public String getUuid ()
    {
        return uuid;
    }

    public double getX()
    {
        return x;
    }

    public double getY()
    {
        return y;
    }

    public double getZ()
    {
        return z;
    }

    public void setUuid (String uuid)
    {
        this.uuid = uuid;
    }

    public void setX(double x) 
    {
        this.x = x;
    }

    public void setY(double y)
    {
        this.y = y;
    }

    public void setZ(double z)
    {
        this.z = z;
    }
}
```

**Comment by j256** [comment]
Ok.  I see nothing there that would generate a VARCHAR(20).  Without a `width = 20` field.  ORMLite wouldn't have done that magically.  Either the table existed before or maybe a version of the class specified the field width.  Best of luck.
