### ISSUE TITLE
QueryBuilder limit has problem in jdbc with Oracle

### ISSUE THREAD

**Issue by wenerme** [j256/ormlite-jdbc#4]
In jdbc:odbc, the Statement `select top 10 * from mytable` is correct.but the builder generated `select * from mytable limit 10` with will throw an exception.

`java.sql.SQLException: Could not build prepared-query iterator for class blog.Article`

**Comment by j256** [comment]
I'm going to close this because I can't figure out what the appropriate Oracle fu is.  Someone is free to reopen if they have more information.

**Comment by martinbaste** [comment]
Hi! I'm having this exact same problem. The exception after the change is the following: 
`java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected`
before the change it was:
`java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended`

Any other suggestions?

Thanks!
