### ISSUE TITLE
How to connect two entities in different tables

### ISSUE THREAD

**Issue by wherkamp** [j256/ormlite-jdbc#41]
```java
//User
@DatabaseTable
public class User {
    @DatabaseField(generatedId = true)
    private int id;
    @DatabaseField
    private String name;

    @ForeignCollectionField
    private ForeignCollection<Group> groups;
//Group Stuff
@DatabaseTable()
public class Group {
    @DatabaseField(generatedId = true)
    private int id;

    @DatabaseField(foreign = true, foreignAutoRefresh = true)
    private User user;
    @DatabaseField
    private String name;
}
```

I have Getters, Setters, and a constructor.     So I create a group with a random name.   Now I have two users.   Person One and person Two. They can both be apart of the group above. . How does that work?    Because a Group takes in a User (I don't know why)?

Does this make sense? I am kinda confused on my part.

**Comment by wherkamp** [comment]
https://github.com/wherkamp/LearnORMLiteBeforeIThrowMyPcOutTheWindow
Ok, so this was my answer. have another table to hold the UserGroups. The groups the user is apart of?
https://github.com/wherkamp/LearnORMLiteBeforeIThrowMyPcOutTheWindow

**Comment by wherkamp** [comment]
I know how to connect two tables. 
Groups can be shared by multiple users. So User 1 and User 2 can both be apart of the group member.  So in the explanation the order is only used by one Account. So in my example above I had a table to hold the groups the user is apart of. And maybe my brain is failing.

**Comment by j256** [comment]
Right but 2 orders can be associated with 1 account.  In your case, the Account is the Group and the Order is the User.  How is it different?

**Comment by wherkamp** [comment]
Ok, thank you. Sorry for bothering you.
