### ISSUE TITLE
Duplicate package names in core and jdbc jars

### ISSUE THREAD

**Issue by janrosseel** [j256/ormlite-jdbc#45]
Both the core and jdbc libraries contain the com.j256.ormlite.db and com.j256.ormlite.logger pacakages. 

This creates issues when wrapping the respective jars as OSGi bundles. The bundling code sees a dependency on the .db package in the core library and the Equinox classloader will then only consider the .db package from the core library. This results in ClassNotFoundException for classes such as com.j256.ormlite.db.DatabaseUtilsType 

Could you please rename the .db and .logger packages in the jdbc library to something else so this conflict goes away in the future?

**Comment by j256** [comment]
This has been fixed in 5.2 that was just released.  Sorry for the delay.
