### ISSUE TITLE
Update not null columns

### ISSUE THREAD

**Issue by dujianchi** [j256/ormlite-jdbc#49]
can it only update not null columns?

**Comment by noordawod** [comment]
Unsure what you really mean... Can you provide an example to showcase what you want?

**Comment by dujianchi** [comment]
I have code like this:
```
class User{
    Long id;
    String name;
    String password;
    String address;
}
....
Dao<User,Long> userDao = ....
....
User user = new User();
user.id=1;
user.name="test";
user.password="test";
user.address="test";
userDao.create(user);
```  
and I wan to update user's address where id=1, I want do this:
```
User user = new User();
user.id=1;
user.address="new address";
userDao.update(user);
```
and then, it throw exception that some colum can not be null

**Comment by noordawod** [comment]
Ahh, got it.

The `update()` method is an all-in method so it will consider all columns. So you should use the `updateBuilder()` instead, something like this:

```java
final UpdateBuilderUser, Long> builder = userDao.updateBuilder();
builder
  .updateColumnValue("address", "new address")
  .where().idEq(1);
builder.update();
```

**Comment by j256** [comment]
Another way to do this is to get the user from the database and _then_ update it.

    User user = userDao.queryForId(1);
    user.address="new address";
    userDao.update(user);

That's how it is supposed to work.  Or, as @noordawod  said, you should use the `UpdateBuilder`.
