### ISSUE TITLE
broken links in §7 (example code) of documentation

### ISSUE THREAD

**Issue by Luthien-in-edhil** [j256/ormlite-jdbc#59]
hi,
thanks for this great ORM library! This is exactly what I was looking form with Hibernate, Jooq or what have you all being way too bulky for my need. 

I'd just like to point to some links in the documentation that seem to be broken: while browsing [§7.1 (code examples)](https://ormlite.com/javadoc/ormlite-core/doc-files/ormlite.html#Examples) I noticed that links like this one: 

> Simple, basic
> This is a simple application which performs database operations on a single class/table. See the [source code](http://ormlite.com/docs/example-simple).

point to https://github.com/j256/ormlite-jdbc/tree/master/src/test/java/com/j256/ormlite/examples/simple which results in a 404 - it looks as if it should have been [github.com/j256/ormlite-jdbc/...../j256/ormlite/:heavy_plus_sign:**jdbc**:heavy_plus_sign:/examples/simple](https://github.com/j256/ormlite-jdbc/tree/master/src/test/java/com/j256/ormlite/jdbc/examples/simple  "ormlite/ jdbc /examples") instead.

best regards,
Lúthien

**Comment by j256** [comment]
Thanks so much @Luthien-in-edhil .  I think I've fixed them all.  Luckily I had them as a redirect so I could fix the path easily.  

Let me know if you find any other problems.
