### ISSUE TITLE
NullPointerException when use JdbcSingleConnectionSource

### ISSUE THREAD

**Issue by Nexxxt99** [j256/ormlite-jdbc#60]
Hello! I am using JdbcSingleConnectionSource as connection service and I get NullPointerException when I try to call one of DaoManager.createDao or TableUtils.createTableIfNotExists. The problem seems to be that 
[`this.sqlConnection = sqlConnection;` ](https://github.com/j256/ormlite-jdbc/blob/7e450a79c12202742eea97c9d14f260d617a734c/src/main/java/com/j256/ormlite/jdbc/JdbcSingleConnectionSource.java#L64) 
assigned after 
[`this.connection = new JdbcDatabaseConnection (sqlConnection)`](https://github.com/j256/ormlite-jdbc/blob/7e450a79c12202742eea97c9d14f260d617a734c/src/main/java/com/j256/ormlite/jdbc/JdbcSingleConnectionSource.java#L70) 
is called.

Thanks!

**Comment by j256** [comment]
Wow.  Huh.  ENOGOOD. You can work around it by using the `new JdbcDatabaseConnection ()` and the set methods and then call `initialize()`.  I'll get it fixed in the next release.
