### ISSUE TITLE
Being able to create a JdbcConnectionSource using an existing Connection

### ISSUE THREAD

**Issue by natinusala** [j256/ormlite-jdbc#8]
Hello,

I would like to use both ORMLite and the standard Connection system of JDBC at the same time, but I don't want to have two connections to my database, so is there a way to be able to create a JdbcConnectionSource using an existing JDBC Connection, or a way to use ORMLite without creating a new connection ?

Thanks !

**Comment by j256** [comment]
Good idea.  Added `JdbcSingleConnectionSource` to trunk.  Will be in 4.49.  See: https://github.com/j256/ormlite-jdbc/commit/6af5c7d07d7029eafa65f4de1a790283b06c5c1d
