### ISSUE TITLE
Statement getGeneratedKeys

### ISSUE THREAD

**Issue by bosborn** [j256/ormlite-jdbc#82]
xerial SQLite JDBC has removed `Statement#getGeneratedKeys` support in [release 3.43.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.43.0.0).

Issue: xerial/sqlite-jdbc#329
Commit: xerial/sqlite-jdbc@712a8a5
Discussion: xerial/sqlite-jdbc#959

Would it be possible to replace getGeneratedKeys usage with a [RETURNING](https://www.sqlite.org/lang_returning.html) clause?  I did something similar in our library here: ngageoint/geopackage-java@f1579b94f9

https://github.com/j256/ormlite-jdbc/blob/c03005aad779e35bc6174c54b6b7367a87f9491f/src/main/java/com/j256/ormlite/jdbc/JdbcDatabaseConnection.java#L188
https://github.com/j256/ormlite-jdbc/blob/c03005aad779e35bc6174c54b6b7367a87f9491f/src/test/java/com/j256/ormlite/jdbc/JdbcDatabaseConnectionTest.java#L125

**Comment by bosborn** [comment]
Probably the same issue as j256/ormlite-core#288

**Comment by Phoenix616** [comment]
PR was merged and [3.45.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.45.0.0) with it released.

**Comment by bosborn** [comment]
Version [3.45.0.0](https://github.com/xerial/sqlite-jdbc/releases/tag/3.45.0.0) is working for my tests.  The `fix` is to avoid xerial SQLite JDBC versions `3.43.0.0` through `3.44.1.0` (upgrade from `3.42.0.1` or before to `3.45.0.0` or later).

**Comment by j256** [comment]
Anything that ormlite should be doing here?  Should I detect the support for get generated-keys and generate different SQL somehow?

**Comment by Phoenix616** [comment]
Ideally `DatabaseMetaData#supportsGetGeneratedKeys()` would be checked and different code be used if that returns false. For SQLite the issue was fixed in the mentioned Xerial SQLite JDBC driver update so it's not that urgent anymore to adjust in ORMLite but it could be helpful for people trying to use ORMLite with a JDBC driver that doesn't support it.
