### ISSUE TITLE
Truncate is supported in SQL Server

### ISSUE THREAD

**Issue by wrose504** [j256/ormlite-jdbc#9]
Hi,

I noticed that TableUtils.clearTable wasn't using TRUNCATE on SQL Server as the SqlServerDatabaseType doesn't override isTruncateSupported(). If I override this myself then TRUNCATE works fine. You may wish to add this to the SqlServerDatabaseType.

Here's how I tested it:
```java
    DatabaseType databaseType = DatabaseTypeUtils.createDatabaseType(jdbcUrl);

    // Enable truncate on SQL server
    if(databaseType instanceof SqlServerJtdsDatabaseType) {
        databaseType = new SqlServerJtdsDatabaseType() {
            @Override
            public boolean isTruncateSupported() {
                return true;
            }
        };
    }

    return new JdbcConnectionSource(jdbcUrl, username, password, databaseType);
```

**Comment by j256** [comment]
Thanks.  Fixed.   See: https://github.com/j256/ormlite-jdbc/commit/12554447b43bea4f63e281e0ecd3844ec6875048
